export const PROJECTS_PAGE = [
  {
    id: "interiorpainting",
    title: "Interior Painting",
    images: [
      "/images/interior/inter1.jpg",
      "/images/interior/inter2.jpg",
      "/images/interior/inter3.jpg",
      "/images/interior/inter4.jpg",
      "/images/interior/inter5.jpg",
      "/images/interior/inter6.jpg",
      "/images/interior/inter7.jpg",
      "/images/interior/inter8.jpg",
      "/images/interior/inter9.jpg",
      "/images/interior/inter10.jpg",
      "/images/interior/inter11.jpg",
      "/images/interior/inter12.jpg",
    ],
    colSpan: [1, 2, 2, 1, 1, 2],
  },
  {
    id: "exteriorpainting",
    title: "Exterior Painting",
    images: [
      "/images/home-remo/home-rem1.jpg",
      "/images/exterior/ext1.jpg",
      "/images/exterior/ext2.jpg",
      "/images/exterior/ext3.jpg",
      "/images/exterior/ext4.jpg",
      "/images/exterior/ext5.jpg",
      "/images/exterior/ext6.jpg",
      "/images/exterior/ext7.jpg",
      "/images/exterior/ext8.jpg",
      "/images/exterior/ext9.jpg",
      "/images/exterior/ext10.jpg",
      "/images/exterior/ext11.jpg",
    ],
    colSpan: [2, 1, 1, 2, 2, 1],
  },
  {
    id: "bathremodeling",
    title: "Bathroom Remodeling",
    images: [
      "/images/bath/bathroom1.jpg",
      "/images/bath/bath2.jpg",
      "/images/bath/bath3.jpg",
      "/images/bath/bath4.jpg",
      "/images/bath/bath5.jpg",
      "/images/bath/bath6.jpg",

      "/images/home-remo/home-rem2.jpg",
      "/images/home-remo/home-rem1.jpg",
      "/images/home-remo/home-rem3.jpg",
      "/images/home-remo/home-rem1.jpg",
    ],
    colSpan: [1, 2, 2, 1, 1, 2],
  },
  {
    id: "kitchenremodeling",
    title: "Kitchen Remodeling",
    images: [
      "/images/kitchen/kitch1.jpg",
      "/images/kitchen/kitch2.jpg",
      "/images/kitchen/kitch3.jpg",
      "/images/kitchen/kitch4.jpg",
      "/images/kitchen/kitchen1.jpg",
      "/images/home-remo/home-rem1.jpg",
      "/images/home-remo/home-rem1.jpg",
      "/images/home-remo/home-rem1.jpg",
      "/images/home-remo/home-rem1.jpg",
      "/images/home-remo/home-rem1.jpg",
      "/images/home-remo/home-rem2.jpg",
    ],
    colSpan: [1, 2, 1.5, 2, 2, 1],
  },
];
